server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/geekshop
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=clave-secreta-muy-larga-para-desarrollo-local-minimo-32-caracteres
jwt.expiration=86400000

cloudinary.cloud-name=placeholder
cloudinary.api-key=placeholder
cloudinary.api-secret=placeholder